QBO_TOKEN_URL: 'https://oauth.platform.intuit.com/oauth2/v1/tokens/bearer'
QBO_AUTH_HOST: "https://appcenter.intuit.com/connect/oauth2"
QBO_API_HOST: "https://sandbox-quickbooks.api.intuit.com"
QBO_BASE_API_URI: "https://sandbox-quickbooks.api.intuit.com/v3/"
QBO_API_MINOR_VERSION: 35

XERO_TOKEN_URL: "https://api.xero.com/oauth/RequestToken"
XERO_AUTH_HOST: "https://api.xero.com/oauth/Authorize"
XERO_ACCESS_URL: "https://api.xero.com/oauth/AccessToken"
XERO_API_URL: "https://api.xero.com/api.xro/2.0"
XERO_FILES_URL: "/files.xro/1.0"
XERO_PAYROLL_URL: "/payroll.xro/1.0"

OAUTH1_BASE_REDIRECT_URI: "https://sandbox-test.api.next.pwc.com/ingestion-consent/v1/xero/{}/callback"
LOGIN_BASE_REDIRECT_URI: "https://acuit-gl-sync-test-0.appspot.com/linker/{}/{}/login"

ADDITIONAL_ENV_VARS: |-
  DATAFLOW_REGION: asia-northeast1
